### ISSUE TITLE
Reply button icon doesn't reply

### ISSUE THREAD

**Issue by esjewett** [microdotblog/microblog-react#27]
The reply button icon on posts in main timeline opens thread instead of reply.

![image](https://user-images.githubusercontent.com/4822/231471547-8b5be538-2d89-4163-b84b-9e66bb56a351.png)

**Comment by manton** [comment]
This is an issue on Mac too, and the fix should apply to both.

**Comment by vincentritter** [comment]
There is tweak to this now available.

We've talked internally and we probably will re-work the markup soon, so to handle better click/tap handling.

I'll close this for now, but feel free to re-open.
