### ISSUE TITLE
Double posts when replying

### ISSUE THREAD

**Issue by manton** [microdotblog/microblog-react#29]
At least on Android, there appears to be a bug when replying where the reply is sent twice. Might only happen when viewing a conversation first.

**Comment by vincentritter** [comment]
I've got a potential fix for this.

We now create a `reply_id` that updates every time the reply screen is opened. It's just using the current timestamp.

We then send this along to the `MicroBlogApi` and set this as a local variable, which means it should be super quick to update, without having to rely on a model/state update.

If it is duplicate, we return a `DUPLICATE_REPLY` status to the call. If that is returned, we assume it went through. I will change this behaviour a little, but like to check this actually fixes the issue first.

Potentially we could also pass along that `reply_id` to the server if we wanted to double check it there also, alongside the conversation id.

I'll close this issue for now, but we can re-open it if it does happen again.
