### ISSUE TITLE
Disable Pinch to Zoom

### ISSUE THREAD

**Issue by otaviocc** [microdotblog/microblog-react#32]
In the current beta it's possible to pinch to zoom. I'm not sure the value it adds, so maybe it could be disabled.

Version 3.0 (Build 310)

<img src="https://otavio.cc/uploads/2023/86fce2c9f3.png" height="600" alt="" />

<img src="https://otavio.cc/uploads/2023/01a4336e3f.png" height="600" alt="" />

**Comment by manton** [comment]
@vincentritter I'm taking a look at this.

**Comment by manton** [comment]
Fixed for the next beta.
