### ISSUE TITLE
Highlight button is hidden

### ISSUE THREAD

**Issue by otaviocc** [microdotblog/microblog-react#34]
Hi there,

The highlight button is hidden behind the iOS contextual menu.

I'm no sure if it's possible to handle this in React, but it would definitely improve the Reading/Highlighting experience.

Thanks!

![image](https://user-images.githubusercontent.com/139272/235296301-eb5c308d-2007-4002-9fb2-d0794e611ca2.png)

**Comment by manton** [comment]
For now you should be able to tap on the selected text to hide the menu. I'd love to eventually put "Highlight" directly in the standard menu, but I'm not sure if that is possible. We may need to just rearrange where the button appears.

**Comment by vincentritter** [comment]
We deployed a tweak to this a few weeks ago, so let me know if this works better. Will close for now.
