### ISSUE TITLE
New uploads always use default blog

### ISSUE THREAD

**Issue by manton** [microdotblog/microblog-react#43]
I think from the Uploads screen, it's not actually using the client's selected blog. Haven't fully investigated yet.

**Comment by manton** [comment]
@vincentritter Uploads screen. Post editor seems good.

**Comment by vincentritter** [comment]
We now handle this correctly as per commit. It wasn't using the correct "temp" upload location that is triggered when you change the site.

Thanks for spotting.

**Comment by manton** [comment]
Excellent. 👍
