### ISSUE TITLE
Alt text for share sheet photos

### ISSUE THREAD

**Issue by manton** [microdotblog/microblog-react#47]
Don't think we support tapping an attached photo to prompt for accessibility description from the share sheet.

**Comment by vincentritter** [comment]
I did want to add a "prompt", but we can't launch prompts in the share sheet. So I'll come with something to show this inline above the image perhaps.

**Comment by manton** [comment]
Hmm, is this a React Native limitation or something else? I don't think there's any problem showing a modal view in a share sheet as far as iOS is concerned.

Let's explore this a little more before we change the UI. It doesn't seem right to have a different UI for setting alt text in the share sheet vs. the normal app. And I think the UI we have in the normal app is good.

**Comment by vincentritter** [comment]
This is our implementation. I need to take a look into this then and rework it.We don’t make use of the navigation library at all. Only a view for now.Leave it with me to experiment with.— VincentOn 9 Jun 2023, at 17:20, Manton Reece ***@***.***> wrote:﻿
Hmm, is this a React Native limitation or something else? I don't think there's any problem showing a modal view in a share sheet as far as iOS is concerned.
Let's explore this a little more before we change the UI. It doesn't seem right to have a different UI for setting alt text in the share sheet vs. the normal app. And I think the UI we have in the normal app is good.

**Comment by vincentritter** [comment]
This has been implemented in the 3.1 release.
