### ISSUE TITLE
Alt text screen scrolling

### ISSUE THREAD

**Issue by manton** [microdotblog/microblog-react#48]
Minor but writing this down so I don't forget. I think a couple tweaks would be good to the alt text screen:

* Don't scroll the image off screen when focusing the text field, if possible. Feels like it scrolls too much currently.
* Don't allow swiping to dismiss the modal, because that dismisses the post editor too.

**Comment by vincentritter** [comment]
To fix the second issue, we now check when the post screen appears and disappears. This triggers a swipeToDismiss option merge with the Navigation library, so only the initial screen can be swiped to dismiss.

**Comment by manton** [comment]
Great, thanks!
