### ISSUE TITLE
Posting photo to external blog returns `undefined` for photo URL

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/microblog-react#52]
When trying to post an image, the image URL is not present in the data sent to the Micropub server.

Steps to reproduce:

* Start a new post
* Add an image – this gets uploaded using the media endpoint
* Add some post text
* Publish the post

With Indiekit, this results in the following post file being created:

```md
---
date: 2023-06-30T22:19:40.234+01:00
photo:
  - url: undefined
    alt: Alt 1
---

Test post 1
```

It would seem that Micro.blog is unable to get the `url` returned by the media endpoint, and/or fails to add this to the submitted post data.

Notes:

* I have tested the same flow using [Quill](https://quill.p3k.io), and it works as expected
* The ‘Uploads’ sheet shows previously uploaded images

**Comment by bwlng** [comment]
It appears this is a result of the app expecting the url to be in the response body.

https://github.com/microdotblog/microblog-react/blob/370ec3756e572e6782c53fec313568a8be551fa4/src/stores/models/posting/MediaAsset.js#L27-L32

In the previous version of the iOS client, the [uploaded image’s URL was pulled from the location header](https://github.com/microdotblog/microblog-ios/blob/18ee225c72fc3951a8bcaa64b76071629f558579/Snippets/Source/RFPostController.m#L1379) which matches the [Micropub recommendation for the Media Endpoint response.](https://www.w3.org/TR/micropub/#response-3)

```
HTTP/1.1 201 Created
Location: https://media.example.com/file/ff176c461dd111e6b6ba3e1d05defe78.jpg
```

**Comment by manton** [comment]
Thanks, we can fix this for the next version.

**Comment by vincentritter** [comment]
Got a fix for this.
