### ISSUE TITLE
Help for contributors: signing into the app within the iOS simulator

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/microblog-react#54]
Given I’ve filed a few bugs, I’d like to test some possible fixes. I’ve cloned the repo, installed all the dependencies and got the app running in the Simulator… and now I need to sign in to the app.

Is there a way to set up the project for local development where authentication can be provided outside of the app? Otherwise, how can I sign into the app using a verification link sent by email?

**Comment by manton** [comment]
Good question, it is tricky to test completely separate from Micro.blog right now without running your own copy of the web app, which isn't open source yet.

**Comment by vincentritter** [comment]
@paulrobertlloyd – if you enter the email address you want to sign in with, it will send you an email (obviously 😅) – that contains a link you can copy and paste into Safari on the Simulator and it should just work.

**Comment by vincentritter** [comment]
Oh and I forgot to mention that you can always sign in using an app token, that you can find on your account page on the website – just copy and paste it and it'll work in the email field (in the app).
