### ISSUE TITLE
When editing post, don't allow swipe to dismiss on post modal

### ISSUE THREAD

**Issue by vincentritter** [microdotblog/microblog-react#72]
Because we changed the behaviour of loading edits, which basically purges them when the editor closes, plus that we're usually normally "re-hydrating" the post as soon as we load up the editor, we need to disallow a swipe to dismiss.

This was brought up here: https://help.micro.blog/t/mb-app-bug-careless-scrolling-with-lose-edits/2207.

Please also update the above post on help once fixed.

**Comment by manton** [comment]
@vincentritter If you haven't started on this, I'm going to make this change. I'm looking at a couple other editing tweaks too.

**Comment by manton** [comment]
Putting my changes in branch more-little-tweaks.

**Comment by manton** [comment]
I've made the change. I also decided to disable swipe to dismiss in all the text editing modals: edit post, new post, reply. Seems more consistent that way.

**Comment by manton** [comment]
Closing, this will be in 3.2.2.
