### ISSUE TITLE
Empty green banner shown when returning from sign in email

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/microblog-react#88]
Steps to reproduce, from signed out app:

1. Enter email into email input
2. Green banner shown prompting user to check their email
3. Click on link from email
4. Asked if want to open in Micro.blog
5. Click ‘Open’
6. Return to app, green banner still shown, but with no text
7. Clicking on timeline dismisses banner

<img src="https://github.com/user-attachments/assets/602fe07f-6b20-48d0-92af-6ebdb67eb14a" width="320" alt="Screenshot of homescreen with green banner shown at bottom.">

**Comment by manton** [comment]
Thanks, I'll get this fixed. Should either hide the green banner after a few seconds or when the sign-in completes.

**Comment by manton** [comment]
Fixed for the next release.
