### ISSUE TITLE
Photo incorrectly resized and published rotated

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/microblog-react#91]
I tried posting an image, but it got rotated before being cropped (and resized?) to its original dimensions.

## Original image

I can’t upload the original JPEG image as it’s 12.9 MB, but here’s a smaller version:

![DSCF2664](https://github.com/user-attachments/assets/77440d2c-0337-42d8-9170-165204657099)

## Image as it appears in Micro.blog iOS

Micro.blog iOS 3.3 (319) appears to rotate the image before cropping it to the original proportions:

<img src="https://github.com/user-attachments/assets/1810d877-0bb0-4ed3-8829-63d394f51d4f" width="320" alt="Screenshot of new post screen, with photo shown as a thumbnail">

<img src="https://github.com/user-attachments/assets/c55152fb-803b-4bfb-8554-4826e98031de" width="320" alt="Screenshot of accessible text screen.">

## Image as it finally appears on website

When the image appears on the website posted to, the cropping appears _not_ to have happened, however the image _has_ been rotated:

![image](https://github.com/user-attachments/assets/36cf644d-127a-4848-bb0f-fb43a972b91c)

**Comment by manton** [comment]
I'm a little skeptical this is a client-side bug. The cropping we used to do in the app is disabled in the current builds. Can you reproduce this with a new image? Wondering if either the EXIF orientation info is wrong or not being processed on the server.

**Comment by paulrobertlloyd** [comment]
Fixed the offending issue with Indiekit here: https://github.com/getindiekit/indiekit/commit/758a92963928b167042cfe321397e2f79938aeda. By passing images via Sharp, all EXIF data was getting stripped prior to any transformations being applied; rotating the image prior to transforming prevents incorrect rotation happening.

Apart from the potential issue with image masking on the accessibility description screen, that issue also goes away now that the above issue is fixed, so perhaps nothing really to worry about there.
